# Site
name: "k-drn"
title: "k-drn"
description: ""
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
google_analytics: 'UA-220309016-2'
disqus: 'k-drn'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  youjung-hong:
    name: youjung-hong
    display_name: youjung-hong
    avatar: 'assets/images/logo.png'
    email:
    web:
    description: ""
  yayyz:
    name: yayyz
    display_name: yayyz
    avatar: 'assets/images/logo.png'
    email:
    web:
    description: ""
  lemon-kim:
    name: lemon-kim
    display_name: lemon-kim
    avatar: 'assets/images/logo.png'
    email:
    web:
    description: ""
  jsunny-kim:
    name: jsunny-kim
    display_name: jsunny-kim
    avatar: 'assets/images/logo.png'
    email:
    web:
    description: ""
  ag-lee:
    name: ag-lee
    display_name: ag-lee
    avatar: 'assets/images/logo.png'
    email:
    web:
    description: ""
  sung-eun:
    name: sung-eun
    display_name: choüè∞
    avatar: 'assets/images/sung-eun/avatar.png'
    email: essie.cho94@gmail.com
    web: https://essie-cho.com
    description: "üê•"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
